console.log("-------------Entero---------------- ");
console.log(4/7);
console.log(1/3.2);
console.log(1/'d');
console.log(1/true);
console.log(1/"hola");
console.log("-------------Decimal---------------- ");
console.log(4.3/7);
console.log(1.2/3.2);
console.log(1.5/'d');
console.log(1.5/' ');
console.log(1.4/true);
console.log(1.3/"hola");
console.log("-------------Caracter---------------- ");
console.log('a'/7);
console.log('a'/3.2);
console.log('a'/'d');
console.log('a'/true);
console.log('a'/"hola");
