console.log(1+1);
console.log(1+1.2);
console.log(1+true);
console.log(1+'a');
console.log(1+"hola");
console.log("--------- decimal ----------");
console.log(1.1+1);
console.log(1.2+1.2);
console.log(1.3+true);
console.log(1.4+'a');
console.log(1.5+"hola");
console.log("--------- bool ----------");
console.log(true+1);
console.log(true+1.2);
console.log(true+true);
console.log(true+'a');
console.log(true+"hola");
console.log("--------- char----------");
console.log('a'+1);
console.log('a'+1.2);
console.log('a'+true);
console.log('a'+'a');
console.log('a'+"hola");
console.log("--------- cadena----------");
console.log("hola"+1);
console.log("hola"+1.2);
console.log("hola"+true);
console.log("hola"+'a');
console.log("hola"+"hola");

