
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LISTA = 18;
  public static final int AS = 44;
  public static final int BOOL = 30;
  public static final int ARROW = 39;
  public static final int GETLIST = 20;
  public static final int APPEND = 19;
  public static final int CONTINUAR = 42;
  public static final int BREAKK = 41;
  public static final int POTENCIA = 56;
  public static final int MAYOR = 64;
  public static final int COMMA = 17;
  public static final int MMMAIN = 70;
  public static final int RBRACE = 14;
  public static final int RPAREN = 11;
  public static final int MENIGUAL = 63;
  public static final int toSTRING = 47;
  public static final int METODO = 69;
  public static final int DOUBLE = 29;
  public static final int STRUCT = 48;
  public static final int LBRACE = 13;
  public static final int LPAREN = 10;
  public static final int FALSE = 27;
  public static final int NOT = 68;
  public static final int MATCH = 38;
  public static final int MULTI = 54;
  public static final int MUTB = 7;
  public static final int RCORCH = 16;
  public static final int INCREMENTO = 49;
  public static final int LCORCH = 15;
  public static final int ENTERO = 3;
  public static final int MODULO = 58;
  public static final int CHARV = 31;
  public static final int TRUE = 26;
  public static final int IGUAL = 59;
  public static final int WHILE = 36;
  public static final int REVERSELIST = 24;
  public static final int DECIMAL = 4;
  public static final int REMVLIST = 22;
  public static final int IMPRIMIR = 25;
  public static final int DO = 37;
  public static final int FOR = 35;
  public static final int DECREMENTO = 50;
  public static final int DIV = 55;
  public static final int ELSE = 34;
  public static final int MENOS = 52;
  public static final int MENOR = 62;
  public static final int MAS = 51;
  public static final int DOT = 12;
  public static final int INT = 28;
  public static final int LENGTH = 46;
  public static final int EOF = 0;
  public static final int SEMICOLON = 9;
  public static final int DEFAULT = 40;
  public static final int CARACTER = 5;
  public static final int MAYIGUAL = 65;
  public static final int POPLIST = 23;
  public static final int OR = 66;
  public static final int error = 1;
  public static final int IF = 33;
  public static final int RAIZ = 57;
  public static final int ID = 6;
  public static final int CAST = 43;
  public static final int COLON = 8;
  public static final int UMENOS = 53;
  public static final int DIFERN = 61;
  public static final int CADENA = 2;
  public static final int SETLIST = 21;
  public static final int STRING = 32;
  public static final int ROUND = 45;
  public static final int AND = 67;
  public static final int RETURNSTC = 71;
  public static final int EQUALS = 60;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CADENA",
  "ENTERO",
  "DECIMAL",
  "CARACTER",
  "ID",
  "MUTB",
  "COLON",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "DOT",
  "LBRACE",
  "RBRACE",
  "LCORCH",
  "RCORCH",
  "COMMA",
  "LISTA",
  "APPEND",
  "GETLIST",
  "SETLIST",
  "REMVLIST",
  "POPLIST",
  "REVERSELIST",
  "IMPRIMIR",
  "TRUE",
  "FALSE",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHARV",
  "STRING",
  "IF",
  "ELSE",
  "FOR",
  "WHILE",
  "DO",
  "MATCH",
  "ARROW",
  "DEFAULT",
  "BREAKK",
  "CONTINUAR",
  "CAST",
  "AS",
  "ROUND",
  "LENGTH",
  "toSTRING",
  "STRUCT",
  "INCREMENTO",
  "DECREMENTO",
  "MAS",
  "MENOS",
  "UMENOS",
  "MULTI",
  "DIV",
  "POTENCIA",
  "RAIZ",
  "MODULO",
  "IGUAL",
  "EQUALS",
  "DIFERN",
  "MENOR",
  "MENIGUAL",
  "MAYOR",
  "MAYIGUAL",
  "OR",
  "AND",
  "NOT",
  "METODO",
  "MMMAIN",
  "RETURNSTC"
  };
}

